### ISSUE TITLE
Failed to join the data

### ISSUE THREAD

**Issue by totaljfb** [gavinr/geojson-csv-join#1]
Hello Gavin,
I'm new to JavaScript and Github. In your example files, it works. But when I revised the first feature in the geojson file, made its first property name to be "COUNTY" and value to be "Lake of the Woods County", and set the index.js to join with the column name "COUNTY", it doesn't work. Could you please help me figure out if there is a problem with the fie? I appreciate it. For your information, no change for in.csv. Just in.geojson and index.js. 

[files.zip](https://github.com/gavinr/geojson-csv-join/files/288772/files.zip)

**Comment by gavinr** [comment]
Hi, Can you please provide the CSV file you're using?

**Comment by totaljfb** [comment]
Sure, here is the original csv. I want to join based on the column "Geographic area" in csv file, which has county names and the property with "COUNTY" in geojson file.
[in.zip](https://github.com/gavinr/geojson-csv-join/files/290274/in.zip)

**Comment by totaljfb** [comment]
to be clear, my original goal is to join these two file
[aim.zip](https://github.com/gavinr/geojson-csv-join/files/290309/aim.zip)

**Comment by totaljfb** [comment]
Hi Gavin, it seems like I found the problem. In your source code, there is one "searchValue = parseInt(searchValue)", it doesn't make sense if the value is a non-numeric string, parseInt() will return a NaN. For example, parseInt("Collin County") will renturn NaN and thus you can't expect a true result by comparing it with "Collin County". I just commented that line and it works.

**Comment by gavinr** [comment]
@totaljfb thanks for figuring it out. that's what the settings are for at the top are for (https://github.com/gavinr/geojson-csv-join/blob/master/index.js#L5-L7) ... maybe there's a better way to alert about that though?

**Comment by totaljfb** [comment]
Yes, thank you for your help. I guess no need to change, just set the that parameter to be false and it works.
