### ISSUE TITLE
Choropleth Map

### ISSUE THREAD

**Issue by mpbotti** [gavinr/geojson-csv-join#3]
Hi Gavin, 

My name is Marcelo, from Argentina, and I'm building a stand-alone web page to help a friend improving his weekly reports. As he has no access to any server I'm making this page to create some maps using a geojson file for the geometry and a csv file for the weekly updated data. The page also allow the user to edit the title, and subtitle, and to print the map using a sort of input form.

The map I have choose to show the data (at least for this version) is a choropleth map reading the geojson file, and mapping the data inside of it (for a future revision I plan to add a heatmap style map and some other ways to visualize data, but for the time being I'll be happy to have this version working...).

What I would like to do is to merge the geojson geometry with the csv data and map that new info in my map. I tried to do that dynamically without luck, and now I'm trying using your geojson-csv-join script to create an output.geojson and map that, but I'm having some problems implementing your solution. 

I understand that your script merge both files (geojson and csv) and creates a new one, but I don't understand how to make it to run from inside an html file. I've trying using <body onload="index();"> without success, <script src="index.js" defer></script> and nothing happened, or window.onload = function ... but I guess I have to modify your script to built it as a function, right? Is there something I'm missing, or didn't notice? 

I also think that I'll need to add a sentence to delete an existing output.geojson file before create the new one, but I guess I can manage that problem when it pops up...

For the time being, I'm using your script and demo files. I've only change the files path to let my code find your files...

Could you please take a look at my code to help me find a solution?

You can my code and web page at [mpbotti/choropleth](https://github.com/mpbotti/choropleth)

Thanks a lot,
Marcelo

**Comment by gavinr** [comment]
@mpbotti Please see the running instructions here: https://github.com/gavinr/geojson-csv-join#prereq I've only used it in a nodejs environment - I do not think it will work in a browser at this time. PRs welcome for a browser-based workflow! Thanks!
